### ISSUE TITLE
Zombie procesy przy paczkach z inwerem

### ISSUE THREAD

**Issue by A-dead-pixel** [Stowarzyszenie-Talent/talentsio#8]
Na wyzwaniach (docker) pojawiło się trochę zombie procesów będących pozostałością po odpalaniu inwerów przy wrzucaniu paczek. Warto by było coś z tym zrobić.

**Comment by A-dead-pixel** [comment]
*Możemy* po prostu poczekać jakąś dekadę, aż znowu ruszy PR na rework docker setupu, bo w image'u workerów będzie wtedy init iirc.

**Comment by otargowski** [comment]
Możemy też nie mieć tego problemu nie używając dockera na produkcji.
